### ISSUE TITLE
iOS XMLHttpRequest cannot load XXX due to access control checks.

### ISSUE THREAD

**Issue by GeorgeD19** [braintree/braintree-web-drop-in#620] opened 2020-05-01 21:05 UTC
### General information

* SDK/Library version: 1.22.1
* Environment: Sandbox
* Browser and OS: Safari 13 on iOS 13.1.1

### Issue description

When attempting to submit card details using the drop-in UI via Safari 13 on iOS 13.1.1 the UI refreshes and the user can't proceed forward.

See my code below which was adapted from this official guide https://developers.braintreepayments.com/guides/drop-in/setup-and-integration/javascript/v3:

```
<form action="{{controllerURL}}" method="post" name="payment_method_form" id="payment_method_form">
    <div id="dropin-container"></div>
    <button id="submit-button">Pay Now</button>
    <script src="https://js.braintreegateway.com/web/dropin/1.22.1/js/dropin.min.js"></script>
    <script>
    var button = document.querySelector('#submit-button');

    braintree.dropin.create({
        authorization: {{clientToken}},
        container: '#dropin-container'
    }, function (createErr, instance) {
        button.addEventListener('click', function () {
            instance.requestPaymentMethod(function (err, payload) {
                if (!err) {
                    document.getElementById('nonce').value = payload.nonce;
                    document.payment_method_form.submit();
                }
            });
        });
    });
    </script>
</form>
```

This code works absolutely fine on desktop (macOS/windows) and Android (Chrome). 

It fails on iOS 13.1.1 using Safari 13 outputting the following errors in the console:

```
[Error] XMLHttpRequest cannot load https://origin-analytics-sand.sandbox.braintree-api.com/{{marchantID}} due to access control checks. x (hosted-fields-frame.min.html:1:49617) (anonymous function) (hosted-fields-frame.min.html:1:49181)
[Error] XMLHttpRequest cannot load https://api.sandbox.braintreegateway.com/merchants/{{marchantID}}/client_api/v1/payment_methods/credit_cards due to access control checks. x (hosted-fields-frame.min.html:1:49617) (anonymous function) (hosted-fields-frame.min.html:1:48869)
[Error] XMLHttpRequest cannot load https://origin-analytics-sand.sandbox.braintree-api.com/{{marchantID}} due to access control checks. I (dropin.min.js:1:26547) request (dropin.min.js:1:26601) (anonymous function) (dropin.min.js:1:39242) sendEvent (dropin.min.js:1:235035) (anonymous function) (dropin.min.js:1:330055) (anonymous function) promiseReactionJob
[Error] XMLHttpRequest cannot load https://origin-analytics-sand.sandbox.braintree-api.com/{{marchantID}} due to access control checks. I (dropin.min.js:1:26547) (anonymous function) (dropin.min.js:1:26111)
```

**Comment by GeorgeD19** [comment] 2020-05-01 21:25
Just an update on this; I updated to iOS 13.4.1 which resolved this issue. This obviously doesn't resolve this issue for users below this version so it might be worth looking deeper into for those users.

**Comment by crookedneighbor** [comment] 2020-05-01 21:36
One thing I see is that you're not preventing the form from submitting (buttons are `submit` type by default). So it's possible that it's submitting the form before the nonce is available.

Probably want to, at minimum add:

```js
button.addEventListener('click', function (e) {
  e.preventDefault();
```

Going to close this for now, because as you said, updating the os fixes the issue. If we get more people reporting it, we can look into it further.

**Comment by thierryler** [comment] 2021-05-05 20:15
I do have the same problem on macos big sur 11.1, safari 14.0.2, dropin 1.22.1, sdk braintree/braintree_php ^5.0 :-(

**Comment by crookedneighbor** [comment] 2021-05-05 21:16
@thierryler provide us a way to reliably reproduce the issue, and I'm happy to re-open this and investigate.

**Comment by thierryler** [comment] 2021-05-05 21:27
Here is the code I use :

```
<script src="https://js.braintreegateway.com/web/dropin/1.22.1/js/dropin.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

<form method="post" id="pay-form" action="some.php" class="spinnable">
  <input type="hidden" name="nonce" id="nonce" />
  <input type="hidden" name="type" id="type" />
</form>


<div id="dropin-container"></div>
<div class="form-group">
  <input type="submit" id="submit-button" class="btn btn-primary" value="Payer" />
</div>

<script>
  showSpinner();

  let submitButton = document.querySelector('#submit-button');
  let payForm = document.querySelector('#pay-form');
  let nonceInput = document.querySelector('#nonce');
  let typeInput = document.querySelector('#type');

  let threeDSecureParameters = {
    amount: '{{ price }}',
    email: '{{ email }}',
    billingAddress: {
      givenName: '{{ firstname }}',
      surname: '{{ lastname }}',
      countryCodeAlpha2: '{{ countryCode }}'
    },
  };

  braintree.dropin.create({
    authorization: '{{ clientToken }}',
    container: '#dropin-container',
    locale: 'fr_FR',
    threeDSecure: true,
    card: {
      cardholderName: {
        required: false
      },
    },
    paypal: {
      flow: 'checkout',
      amount: '{{ price }}',
      currency: 'EUR'
    }

  }).then(function (dropinInstance) {
    console.log('ready');
    hideSpinner();
    submitButton.addEventListener('click', function (e) {
        showSpinner()

        e.preventDefault();
        dropinInstance.requestPaymentMethod({
          threeDSecure: threeDSecureParameters

        }).then(function (payload) {
            nonceInput.value = payload.nonce;
            typeInput.value = payload.type;
            payForm.submit();

        }).catch(function (error) {
            // Handle error
            console.error(error);
            hideSpinner()
        });
    });

  }).catch(function (error) {
      // Handle error
      console.error(error);
      hideSpinner()
      // TODO popup error
  });

</script>
```

**Comment by crookedneighbor** [comment] 2022-07-27 14:45
Closing due to inactivity.

**Closed by crookedneighbor** 2022-07-27 14:45 UTC
