### ISSUE TITLE
PayPal Method Fails

### ISSUE THREAD

**Issue by azampagl** [braintree/braintree-web-drop-in#792] opened 2022-01-25 18:37 UTC
### General information

* SDK/Library version: 1.32.1
* Environment: Sandbox
* Browser and OS: Chrome (97.0.4692.99), Windows (10, latest updates)

### Issue description

I'm trying to enable PayPal as an option using the web-drop-in using the vault flow. An example code snippet is:

`
this.braintreeInstance = await braintree.dropin.create({
    authorization: token,
    container: '#braintree-container',
    vaultManager: true,
    card: {
        cardholderName: {
            required: true,
        },
     },
    paypal: {
        flow: 'vault',
    },
});
`

The option to select PayPal is avaiable on the UI but when it is clicked it launches a pop up window (which is what I assume an OAuth prompt) and then immediately closes with the following error:

![06](https://user-images.githubusercontent.com/43206/151037883-f13d54b4-111f-482e-a489-4970edc8e72b.PNG)

![0](https://user-images.githubusercontent.com/43206/151038117-e0cb29ac-1745-4e10-ade7-7fd3f096426b.png)

Credit Card submission / storage works with no issues.

This is all in the sandbox environment and I have attached a sandbox PayPal account to the Braintree configuration.

I have also opened a Braintree with more account details: Ticket # 3541742

**Comment by jplukarski** [comment] 2022-01-26 16:12
Hey @azampagl , thanks for using the Drop-In. It looks like you have already reached out to our support team regarding this issue; they will be able to best assist you with why this exact error message is happening in your integration. Typically this error is due to an incorrectly configured PayPal account, and our support team will be able to help you troubleshoot

While they look into your inquiry, I can recommend double-checking the following:
- You have properly [linked a PayPal sandbox test account to your Braintree sandbox account](https://developer.paypal.com/braintree/docs/guides/paypal/testing-go-live#linked-paypal-testing)
- If you are using a client token as your authorization, and you are passing in a [Merchant Account ID](https://developer.paypal.com/braintree/articles/control-panel/important-gateway-credentials#merchant-account-id), that you are passing in a valid Merchant Account ID (not to be confused with your [Merchant ID](https://developer.paypal.com/braintree/articles/control-panel/important-gateway-credentials#merchant-id), as [the two are quite often mixed up](https://developer.paypal.com/braintree/articles/control-panel/important-gateway-credentials#merchant-account-id-versus-merchant-id))

Since this is most likely an issue with your integration and not a bug in our SDK, I am going to close this issue, however, feel free to reopen this issue if you are still unable to find a resolution to this after working with our support team.

Thanks again!

**Closed by jplukarski** 2022-01-26 16:12 UTC
