### ISSUE TITLE
v1.0.0 paypal payment method fails on sandbox

### ISSUE THREAD

**Issue by xDae** [braintree/braintree-web-drop-in#152] opened 2017-05-05 16:06 UTC
### General information

* SDK/Library version: drop-in web v1.0.0
* Environment: sandbox
* Browser and OS: Chrome 58.0.3029.96 (64-bit) on MacOS Sierra -->

### Issue description

After configuring the "final" release of the drop-in (v1.0.0) in a staging enviroment with the sandbox the comunication with paypal fails.

<img width="769" alt="captura de pantalla 2017-05-05 a las 17 58 50" src="https://cloud.githubusercontent.com/assets/6037190/25753898/88d21850-31bd-11e7-8312-fa3105dc2c92.png">

BTW, the credit card payment method works fine.

**Comment by lilaconlee** [comment] 2017-05-05 16:49
@xDae we've investigated a bit, but have not been able to reproduce this issue. If we could take a look at your drop-in create call or get access to a staging site, we could be a little more helpful. We'd also be interested in what beta version you were using before you updated to 1.0.0. Feel free to email us at web-drop-in-beta@getbraintree.com or through our [support team](https://developers.braintreepayments.com/forms/contact) if you rather not provide this information on public GitHub.

**Comment by bkonia** [comment] 2017-05-08 20:11
I'm getting the same error in Beta 7. It was working fine in Beta 5. See attached screenshots.

![dfa0b211-4296-47e6-a5a8-4c16b61f672b](https://cloud.githubusercontent.com/assets/2266423/25823085/c6736176-33ef-11e7-9ab6-f9fcb16a720f.png)
![image](https://cloud.githubusercontent.com/assets/2266423/25823114/dcb6f286-33ef-11e7-9793-e0d528973055.png)

**Comment by crookedneighbor** [comment] 2017-05-08 20:13
Please provide your create call or a staging site so we can inspect it.

**Comment by bkonia** [comment] 2017-05-08 20:25
braintree.dropin.create({
                authorization: '<?php echo Braintree_ClientToken::generate(["customerId" => $currentUser->ID]); ?>',
                selector: '#dropin-container',
                paypal: {
                    flow: 'vault',
                }
            }, function (err, dropinInstance) {
                if (err) {
                    return;
                } else {
                    jQuery(".braintree-option").first().click(function() {
                        jQuery("#submit-button").width(jQuery(".braintree-toggle span").width());
                        jQuery("#submit-button-container").css('visibility', 'visible');
                    });
                    jQuery("#submit-button-container").insertBefore(".braintree-toggle");
                    jQuery(".braintree-toggle span").addClass("bd-button button");
                    jQuery(".braintree-toggle").click(function() {
                        jQuery("#submit-button-container").css('visibility', 'hidden');
                    });
                }
                jQuery('#submit-button').click(function () {
                    dropinInstance.requestPaymentMethod(function (err, payload) {
                        if (err) {
                            return;
                        } else {
                            jQuery("#submit-button-container").css("visibility", "hidden");
                            var data = {
                                action: 'payment_options',
                                security: '<?php echo $ajax_nonce; ?>'
                            };
                            jQuery.post('<?php echo AJAX_URL; ?>', data, function(response) {
                                jQuery('#automatic_payments_method').html(response);
                            });
                            window.location.reload();            
                        }
                    });
                });
            });

**Comment by crookedneighbor** [comment] 2017-05-09 22:27
I have not been able to reproduce the issue. Do either of you have staging sites we could view to reproduce it?

If you'd prefer not to post your staging site link on Github, feel free to email support@braintreepayments.com and mention this issue.

**Comment by bkonia** [comment] 2017-05-09 22:33
I just emailed you login info for a demo account on my site.

**Comment by crookedneighbor** [comment] 2017-05-10 14:27
@bkonia I've reviewed the ticket, and it looks like your PayPal sandbox credentials were not valid. Your credentials have been reset so you can re-enter them with the correct credentials.

@xDae I imagine the same is happening with your account. 

I'm going to close this now, but feel free to comment or continue in the support email if you need further assistance.

**Closed by crookedneighbor** 2017-05-10 14:27 UTC

**Comment by xDae** [comment] 2017-05-10 14:44
@crookedneighbor yes, we already fixed the problem 🤙🏻
