### ISSUE TITLE
Credit Card Field shrinks and is disabled when user click on card icons.

### ISSUE THREAD

**Issue by dadrcheng** [braintree/braintree-web-drop-in#336] opened 2017-12-06 01:42 UTC
### General information

* SDK/Library version: 1.9.0
* Environment: Production
* Browser and OS: Chrome Version 62.0.3202.94 and iPhone 6 Safari

### Issue description
If user click on one of the card image icons, the credit card field will shrink and the field will not expand again or allow user to enter card number.  Refreshing the page will reset it.  I have noticed Expiration Date field will also behave this way if image icons are click but that is a little harder to duplicate.

Please see attach screen shot.
Thanks,
David
![screenshot-www plushnecessities com 2017-12-05 17-41-14-503](https://user-images.githubusercontent.com/32307252/33640137-9dc38720-d9e3-11e7-9555-d59e6947a2c0.jpeg)

**Comment by crookedneighbor** [comment] 2017-12-06 02:17
I cannot reproduce this. Can you:

A) Update to v1.9.2 and verify that it is still happening? 
B) Attempt to reproduce on https://braintree.github.io/braintree-web-drop-in/

**Comment by dadrcheng** [comment] 2017-12-06 02:30
Thanks for the reply.  I am not able to reproduce it in https://braintree.github.io/braintree-web-drop-in/

Perhaps there is some conflicting javascript on my site.  Seems strange as I didn't have this issue with previous versions.  I can't reproduce it every single time.  Sometimes, I have to click on the card icons multiple times.  Customers have also complained.  I recorded a webm video but can't share here.

**Comment by crookedneighbor** [comment] 2017-12-06 02:31
Can you share a url where it happens? Or a github repo that reproduces the issue?

**Comment by dadrcheng** [comment] 2017-12-06 02:33
Would you mind me sharing that info privately?  To your email address "blade@...."?

**Comment by crookedneighbor** [comment] 2017-12-06 03:18
Please contact our support team and reference this issue.

https://developers.braintreepayments.com/forms/contact

**Comment by dadrcheng** [comment] 2017-12-06 03:20
Okay

**Comment by crookedneighbor** [comment] 2017-12-06 14:26
I found your ticket in the system and was able to reproduce both on an iPhone and by setting the web inspector's viewport to an iPhone 6 in dev tools on Desktop Chrome. Investigating what on your site is causing it.

**Comment by crookedneighbor** [comment] 2017-12-06 14:31
I noticed you're using v1.8.1. Can you upgrade to v1.9.2? 

There is, specially, [a fix for some styling issues that may be related to what you're experiencing](https://github.com/braintree/braintree-web-drop-in/blob/master/CHANGELOG.md#191).

**Comment by crookedneighbor** [comment] 2017-12-06 15:25
For the record, the support ticket number is 1767709

**Comment by dadrcheng** [comment] 2017-12-06 17:11
Thanks crookedneighor!   I am going to try these changes late tonight during our slow traffic time and let you know.  Really appreciate your help!

**Comment by crookedneighbor** [comment] 2017-12-07 16:26
I'm going to close this, because I don't _think_ there are any changes that need to be made to the SDK, but feel free to post your findings here.

**Closed by crookedneighbor** 2017-12-07 16:26 UTC

**Comment by dadrcheng** [comment] 2017-12-07 16:28
Thanks for the help.  Using version 1.9.2 and removing the css solved the issue.
