### ISSUE TITLE
Issues with CardHolder Name field in VueJS

### ISSUE THREAD

**Issue by usamaibrahim93** [braintree/braintree-web-drop-in#654] opened 2020-09-03 15:38 UTC
### **General Information**

* SDK/Library version: 1.23.0
* VueJS 2.5.13 using WebPack
* Environment: Production
* Browser and OS: Chrome 84 on Windows 10

### **Issue description**

Hi, 
Thank you for creating this amazing SDK and making lives easier. I've been this on my VueJS app for the past 6 months or so. But this strange issue got reported only recently.

So basically I updated the SDK a few weeks ago hoping the issue would resolve but it didn't. What happens is that sometimes, **CardHolder Name** field in Credit Card section would not allow us to enter a space in order to fill in the complete name.

The issue was reported by a couple of our customer but was not being reproduced on our end. But yesterday, I just stumbled across this same issue. I thought maybe it is an issue with my other scripts or something but my browser's console was not reporting any errors or exception.

I am not a javascript expert so I am not sure what other details need to be provided. I have a recorded video that shows I'm tapping the spacebar but it's not entering any spaces. This is something that has been bugging me for a long time as it provides negative user experience to my customers.

Any help or clues would be really appreciated. Thank you in advance!

**Comment by hollabaq86** [comment] 2020-09-03 15:46
@usamaibrahim93 thanks for reaching out! This definitely sounds frustrating, are you seeing this issue only on Chrome desktop? Are there any other browsers where you're seeing this issue? If you feel more comfortable sending your video privately, please [contact Support](https://help.braintreepayments.com/) referencing this issue with the video and they'll partner with us to investigate.

**Comment by usamaibrahim93** [comment] 2020-09-03 17:09
> @usamaibrahim93 thanks for reaching out! This definitely sounds frustrating, are you seeing this issue only on Chrome desktop? Are there any other browsers where you're seeing this issue? If you feel more comfortable sending your video privately, please [contact Support](https://help.braintreepayments.com/) referencing this issue with the video and they'll partner with us to investigate.

Thank you for your quick response. Yes as of now, I saw this issue on Chrome desktop myself and the few customers that reported this were also using the same. The major challenge here is inability to reproduce issue on demand.

I reached out to BrainTree support directly some time ago. They were of the view that their SDK is not actively built for frameworks like VueJS so it yielded little help. Can you please guide me what to do? Thank you so much sir!

**Comment by usamaibrahim93** [comment] 2020-09-03 17:30
> > @usamaibrahim93 thanks for reaching out! This definitely sounds frustrating, are you seeing this issue only on Chrome desktop? Are there any other browsers where you're seeing this issue? If you feel more comfortable sending your video privately, please [contact Support](https://help.braintreepayments.com/) referencing this issue with the video and they'll partner with us to investigate.
> 
> Thank you for your quick response. Yes as of now, I saw this issue on Chrome desktop myself and the few customers that reported this were also using the same. The major challenge here is inability to reproduce issue on demand.
> 
> I reached out to BrainTree support directly some time ago. They were of the view that their SDK is not actively built for frameworks like VueJS so it yielded little help. Can you please guide me what to do? Thank you so much sir!



> @usamaibrahim93 thanks for reaching out! This definitely sounds frustrating, are you seeing this issue only on Chrome desktop? Are there any other browsers where you're seeing this issue? If you feel more comfortable sending your video privately, please [contact Support](https://help.braintreepayments.com/) referencing this issue with the video and they'll partner with us to investigate.

Bingo. Actually I was able to reproduce it again and again recently. Actually it's only happening on my production environement and not on staging. It occurs when I click and enter cardholder name as soon as the Braintree payment module is loaded on my page. As soon as I click out of the cardholder name field and click back in again, it starts working fine again.

I am clueless what could be causing this Do you have any idea why this could be happening? Thank you!

**Comment by usamaibrahim93** [comment] 2020-09-03 21:31
[spaces_not_working.zip](https://github.com/braintree/braintree-web-drop-in/files/5171493/spaces_not_working.zip)
@hollabaq86  here is the zipped video file in case you want to take a look. Please suggest!

**Comment by crookedneighbor** [comment] 2020-09-08 15:48
Can you provide us with an example repo that can reproduce the issue? There's nothing to my knowledge that should prevent the space key from being used.

**Comment by usamaibrahim93** [comment] 2020-09-08 16:21
> Can you provide us with an example repo that can reproduce the issue? There's nothing to my knowledge that should prevent the space key from being used.

Hi @crookedneighbor . Thanks a lot for getting in touch. We are using a behavior tracking script on our site called Visual Web Optimizer. After a lot of hit and trials, I figured out its causing the issue with Braintree. Turning off the script makes everything work perfectly. Do you think I should carry this forward with Braintree or the actual script vendor?

Thanks again!

**Comment by crookedneighbor** [comment] 2020-09-08 17:50
The script vendor. If you can pinpoint why it's occurring, happy to look into it, but my assumption here is some faulty code on the script vendor's part.

Also, we're soon going to swap out the cardholder name field from a raw html input to a hosted fields input, so even if nothing changes on the vendor's end, it's likely that whatever's happening will cease to happen when the input is inside of a Braintree hosted iframe.

Going to close this issue for now since there's nothing actionable for us.

**Comment by usamaibrahim93** [comment] 2020-09-08 17:51
Thanks That sounds perfect!

**Closed by crookedneighbor** 2020-09-08 17:50 UTC
