### ISSUE TITLE
Chrome showing a  No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by redgenie** [braintree/braintree-web-drop-in#295] opened 2017-10-15 09:06 UTC
### General information
I'm implementing the web drop in in React, when I use it in localhost, everything is fine, but as soon as the code is on a live server, Chrome fails to load braintree (Safari and Firefox are fine) with this error:

> Failed to load https://api.sandbox.braintreegateway.com/merchants/ ... : No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://my.website.com' is therefore not allowed access.

* SDK/Library version: 1.8.0
* Environment: sandbox
* Browser and OS: Chrome 61.0.3163.100 (Official Build) (64-bit) on macOS 10.13.1 Beta

### Issue description
I am using the npm packages: `"braintree-web-drop-in": "^1.8.0"` and `"braintree-dropin-react": "^0.0.2",`. I have a component where I have a button, when I click on the button, it displays the braintree component as such:

```javascript
import React from 'react';
import BraintreeDropin from 'braintree-dropin-react';
import braintree from 'braintree-web-drop-in';


export class MyComponent extends React.PureComponent {

  // ...

  render() {
    <div>
      // This will fetch the token, once the token is there, it changes this.props.showBraintree
      // to true, so the component is not initialized before any token is present.
      // The problem is therefore between Chrome and Braintree
      <button onClick={() => this.fetchTokenAndShowBrainTree()}>Show Braintree</button>

      return (
        {this.props.showBraintree && this.props.token && <BraintreeDropin
        braintree={braintree}
        authorizationToken={this.props.token}
        handlePaymentMethod={this.handlePayment}
        onCreate={this.onCreate}
        />}
      );
    </div>
  }
}
```

**Comment by redgenie** [comment] 2017-10-16 07:17
After checking again, this issue happens only when the Chrome developer tools is open.

**Comment by lilaconlee** [comment] 2017-10-16 20:09
Have you tried integrating braintree-web-drop-in without using `braintree-dropin-react`? We don't maintain `braintree-dropin-react`, but aren't sure if the issue is part of `braintree-web-drop-in` or the wrapper.

Let us know if you have a staging site or test app and we can help debug further as well.

**Comment by crookedneighbor** [comment] 2017-10-30 02:00
Going to close this now, but let us know if you'd like us to take a further look.

**Closed by crookedneighbor** 2017-10-30 02:00 UTC
