### ISSUE TITLE
[3DSecure] [Firefox] Modal doesn't close when there is an error

### ISSUE THREAD

**Issue by Minishlink** [braintree/braintree-web-drop-in#335] opened 2017-12-05 19:23 UTC
### General information

* SDK/Library version: 1.9.1
* Environment: Sandbox
* Browser and OS: Firefox 57.0.1 (64 bits) on MacOS 10.13.1

### Issue description

Hello,

On Firefox, when there is a 3D Secure error, the modal doesn't close. This can be seen in this [codepen](https://codepen.io/braintree/pen/BZWdmy) with the card number `4000000000000051`.

**Comment by crookedneighbor** [comment] 2017-12-05 19:57
Looks like it's not limited to Firefox. Reproduced the issue in Chrome.

Thanks for the report, we'll look into it.

**Comment by Minishlink** [comment] 2017-12-06 06:42
Oh strange I wasn't seeing this on my Chrome. It looks like a race condition

**Comment by crookedneighbor** [comment] 2017-12-13 14:34
The problem happens when no iframe is passed back (which means liability was not shifted). Opened a PR to fix that. https://github.com/braintree/braintree-web-drop-in/pull/338

**Comment by crookedneighbor** [comment] 2017-12-27 16:07
The fix for this will go out in the next release.

**Closed** 2017-12-27 16:06 UTC

**Comment by Minishlink** [comment] 2017-12-27 16:29
Thanks @crookedneighbor!

**Comment by Minishlink** [comment] 2018-01-16 09:26
@crookedneighbor Could you release a new version?

**Comment by crookedneighbor** [comment] 2018-01-16 21:08
I'm shooting for a release at the end of this week, or the beginning of next week.

**Comment by crookedneighbor** [comment] 2018-01-22 20:21
This has been released today as v1.9.3

**Comment by Minishlink** [comment] 2018-01-22 21:44
Thanks @crookedneighbor!
