### ISSUE TITLE
Need to detect an incomplete PayPal / GooglePay / Venmo selection

### ISSUE THREAD

**Issue by simeyla** [braintree/braintree-web-drop-in#459] opened 2018-11-29 20:56 UTC
### General information

* SDK/Library version: Dropin 14.1.1
* Environment: Sandbox

### Issue description

I have some pretty stupid users. 

When selecting PayPal using the drop-in UI you have to then click the express checkout button to continue. Not everybody is smart enough to click this button - in fact I'd argue it doesn't really look like a button to me when it's in a frame like this after you've already selected PayPal. What is the recommended approach to deal with the UI in the below state?

![image](https://user-images.githubusercontent.com/3656278/49250997-3e15cd80-f3d5-11e8-9bf1-213401ec627a.png)

If I call `requestPaymentMethod` when the UI is in this state it gives me the following message:

     {"name":"DropinError","message":"No payment method is available."}

If it were to give me something liek **this** message:

     {"name":"DropinError","message":"No payment method is available.", "incompletePaymentOption": "venmo"}

Then I could display a message accordingly:

* Please click the PayPal Express checkout button to continue to the PayPal website
* Please click the Venmo button to switch to the Venmo app and complete your payment
* Please click the Google Pay button to select a payment method from your Google account

Right now what am I supposed to do? 

* Please click the payment button corresponding to either PayPal, Venmo or GooglePay above 

This is horrible! There has to be a better way. Like I said this only an issue for inexperienced users that need the most guidance, so I'm looking for a friendly solution.

My current custom implementation (not Braintree) has an additional PayPal button at the bottom of the page (under shipping address) that lets the user continue to PayPal. I can't see a way to do something like that here.

**Comment by simeyla** [comment] 2018-11-29 21:05
*Possible solution:*

Am I supposed to 'remember' the last response I get from `paymentOptionSelected`? Which does in fact give me the 'pending' payment type.

**Comment by crookedneighbor** [comment] 2018-11-29 21:46
Closed as a duplicate of https://github.com/braintree/braintree-web-drop-in/issues/433

**Closed by crookedneighbor** 2018-11-29 21:46 UTC
