### ISSUE TITLE
data-collector.min.js doesn't loaded

### ISSUE THREAD

**Issue by wirthandras** [braintree/braintree-web-drop-in#919] opened 2024-01-24 08:19 UTC
We are using advanced fraud protection which requires devicedata information.

Some of our users faced of payment problems related to dropin, since the following javascript file doesn't loaded well, the rest of the scripts and assets seems ok:

```https://js.braintreegateway.com/web/3.96.1/js/data-collector.min.js```

![image](https://github.com/braintree/braintree-web-drop-in/assets/12913003/606818ea-f328-4dbb-a46b-2ee0a7215933)

We are using```braintree-web-drop-in": "^1.38.0"``` in an angular v13 project. 

* Environment: Production
* Browser and OS : Various: 
    Facebook 440.0.0.28.352, iOS 17.1.2
    Chrome 120.0.0.0, Mac OS 10.15.7+
    Safari 15.6.1 Mac OS 10.15.7+
    Safari  16.3, Mac OS 10.15.7+
    Chrome 118.0.0, Mac OS 10.15.7+

I saw the Facebook browser aren't supported.

Can we do anything with this problem?

**Comment by jplukarski** [comment] 2024-02-08 20:56
@wirthandras , thanks for writing in.

It looks like there is a version mismatch here. Version 1.38.0 of the Drop-In should be using version 3.94.0 of the data-collector, which matches the version in the screenshot, but then you point to a data-collector version of 3.96.1. Which version of the drop-in are you actually using, and how are you loading the data-collector? In the drop-in, the correct way to load the data-collector is to pass in `dataCollector: true` in your `dropin.create()` method, [as outlined in our documentation](https://developer.paypal.com/braintree/docs/guides/premium-fraud-management-tools/client-side/javascript/v3#drop-in). Are you loading it separately with a script tag?

Also, can you share the reason it doesn't load? Is there any sort of error message to go along with that screenshot?

Finally, you are correct that [we do not officially support Facebook Browser](https://braintree.github.io/braintree-web/current/#browser-support). This is because the Braintree SDK is not tested or developed with the Facebook browser, so we cannot guarantee it's performance. You can certainly continue to use the SDK within the Facebook browser, but you may run into issues. If you do run into specific issues with the Facebook browser, let us know and we will do our best to resolve that issue.

**Comment by wirthandras** [comment] 2024-02-12 13:29
@jplukarski we updated the related package to ```"braintree-web-drop-in": "^1.42.0",``` that will be go production probably in next week, and yes we are using the option ```dataCollector: true``` which you mentioned. As I mentioned we were used the version 1.38.0 before the update. We are not added anything related to a separated script loading magic like a script tag.

The reason is unclear, we saw only a "failed" message in our monitoring tool. Could be a network problem.

We saw the problem only affected a limited number of users (<10) with various browsers.

**Comment by jplukarski** [comment] 2024-02-12 16:14
@wirthandras thanks for the clarification. Without reason for the failures we would not be able to triage this issue to see if there is a bug in the SDK. I agree it's likely network or browser-related issues on the buyer's end.

We're going to close this issue out for now. If you continue to experience this issue or if you see it start happening more frequently you can [reach out to our support team](https://developer.paypal.com/braintree/help/) with timestamps, SDK version, and, if possible, steps to reproduce.

Thanks

**Closed by jplukarski** 2024-02-12 16:14 UTC
