### ISSUE TITLE
Trying to tab through the credit card form on Safari is not smooth

### ISSUE THREAD

**Issue by PascalMayr** [braintree/braintree-web-drop-in#662] opened 2020-09-16 12:17 UTC
### General information

* SDK/Library version: 1.22.1
* Environment: Sandbox
* Browser and OS Safari Version 13.1.2 (15609.3.5.1.3) on MacOS 10.15.6 (19G2021)

### Issue description

The following steps describe the issue when I try to tab trough the form for credit cards on Safari:
1.) Filling out the credit card number
2.) clicking the Tab ↹ key
3.) the focus is not on the Expiration Date input field **but on the credit card image**
4.) clicking the Tab ↹ key again
5.) The focus is now on the Expiration Date input field
6.) clicking the Tab ↹ key
7.) The focus is now on the **credit card symbol** in the CVV field
8.) clicking the Tab ↹ key
9.) The focus is now on the CVV input

The credit card image and the credit card symbol shouldn't be focused.

**Comment by crookedneighbor** [comment] 2020-09-16 14:12
You're right that the experience is not smooth in Safari, but you're not quite right about what is getting focus here. The problem is that Safari 13 added some new behavior where elements cannot be programmatically focussed unless it is the result of a direct user action. 

So in Chrome, Firefox, etc, our handlers to focus specifically on the input inside the iframe are respected, but in Safari, that focus is prevented. Meaning you need to tab an additional time to enter the input _inside the iframe_. One tab to get to the iframe, and one tab to enter the input.

We're still looking for a solution here.

For reference, this is the underlying bug where we're tracking this: https://github.com/braintree/braintree-web/issues/490#issuecomment-658361207

**Comment by crookedneighbor** [comment] 2021-06-17 16:16
This is now fixed in v1.30.1!

**Closed by crookedneighbor** 2021-06-17 16:16 UTC
