### ISSUE TITLE
Paypal-Button does not work

### ISSUE THREAD

**Issue by Connum** [braintree/braintree-web-drop-in#423] opened 2018-08-24 09:22 UTC
### General information

* SDK/Library version: dropin 1.12.0
* Environment: Sandbox
* Firefox 61.0.2 (64-Bit) on Windows 10

### Issue description
I copied the example code, inserted my generated clientToken as the authorization parameter and added PayPal integration via

	  paypal: {
	    flow: 'vault'
	  }

The PayPal Sandbox account is linked to the Braintree Sandbox account. The payment method selection correctly shows credit card and PayPal. However, when the page loads, there are two errors in the browser's dev console.

    TypeError: styles is null[Weitere Informationen]
    in button.js:56

and

    TypeError: window.setupButton is not a function
    in button:1168:25

When selecting PayPal and clicking the PayPal button, nothing happens (not even new error messages in the console). Why is this happening and what can I do to make it work?

**Comment by crookedneighbor** [comment] 2018-08-24 12:29
Just tried it in Firefox and was able to reproduce. This is definitely an issue with checkout.js. The PayPal team is aware of it and working to fix it.

**Comment by Connum** [comment] 2018-08-24 12:44
Thanks for the feedback! Let's hope it doesn't take too long, it's currently a show-stopper for me to switch to Braintree.

**Comment by crookedneighbor** [comment] 2018-08-24 15:11
The PayPal team has identified the source of the issue and is rolling back the code that introduced it. Will close this issue when it is finished being rolled back.

**Comment by crookedneighbor** [comment] 2018-08-24 18:01
This is fixed in Sandbox. PayPal is still working on rolling back in production.

**Comment by crookedneighbor** [comment] 2018-08-24 18:57
This should be fixed in prod now as well. Going to close this now, but comment here if you're still having issues.

**Closed by crookedneighbor** 2018-08-24 18:57 UTC

**Comment by Connum** [comment] 2018-08-25 09:56
It is indeed fixed, thank you for the super-fast handling of this issue. Please pass on that it would be nice if future changes were tested in all major browsers before deploying to the live systems.

**Comment by crookedneighbor** [comment] 2018-08-26 03:40
I've passed your feedback on to the team that manages checkout.js. This problem only affected integrations that were rendered within a hidden div, I've asked the team to add an integration test for that case since it should be a fairly common pattern.
