### ISSUE TITLE
Finnish Translation Support - Enhancement

### ISSUE THREAD

**Issue by AlexanderCollins** [braintree/braintree-web-drop-in#640] opened 2020-07-23 11:22 UTC
Hi there!

My Finnish team were in need of some Finnish translations so we made some and thought we would share them here!

I read the contributing guideline and it looks like translation requests are not allowed and also would only be included if the language is listed within [PayPal's accepted language codes](https://developer.paypal.com/docs/api/reference/locale-codes/#supported-locale-codes) which luckily appears to be the case. (fi_FI priority 0)

Regarding the translations themselves, I have a native Finnish speaker with C2 english level proficiency who has completed the translations from english and have also had the translations verified by another native Finnish speaker. I've prepared a [pull request: 639](https://github.com/braintree/braintree-web-drop-in/pull/639).

It would be great if this could be escalated to the localisation team for verification. In the mean time we will use the translations directly with the translations prop as per the [braintree-web-drop-in documentation](https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#create-examples).

Many Thanks!

**Comment by crookedneighbor** [comment] 2020-07-23 15:23
Closing as a duplicate of #641

**Closed by crookedneighbor** 2020-07-23 15:23 UTC
