### ISSUE TITLE
When Entering Invalid test credit cards, drop-in throws and error

### ISSUE THREAD

**Issue by jmannau** [braintree/braintree-web-drop-in#403] opened 2018-05-25 04:54 UTC
### General information

* SDK/Library version: 1.11.0
* Environment: Sandbox
* Browser and OS:  Chrome Version 66.0.3359.181 on MacOs 10.13.4 

### Issue description

Thanks for the great library!

I am using the Drop-In to accept credit cards and was testing cards from (https://developers.braintreepayments.com/guides/credit-cards/testing-go-live/php#card-numbers-for-unsuccessful-verification) to check for invalid cards. 

In the sandbox account settings, I have enabled 'Card Verification' prior to storage in the Vault. 

When using test cards '4000...1115' or '5105...5100' there is an error when trying to add a credit card. 

```
Uncaught TypeError: Cannot read property 'creditCard' of null
    at p.t.exports [as _adapter] (hosted-fields-frame.min.html:1)
    at p.adaptResponseBody (hosted-fields-frame.min.html:1)
    at XMLHttpRequest.O.f.onreadystatechange (hosted-fields-frame.min.html:1)
```

This is cased as the post to https://payments.sandbox.braintree-api.com/graphql response returns
```
{
  "data" : {
    "tokenizeCreditCard" : null
  },
  "extensions" : {
    "requestId" : "..."
  }
}
```

This then leaves the UI in a locked 'loading' state. (see screenshot).

![screen shot 2018-05-25 at 2 51 06 pm](https://user-images.githubusercontent.com/175909/40526633-18e27ea2-602b-11e8-91b8-3767b3acd2ff.png)

Can the Drop-In UI Handle verification of invalid cards?

**Comment by crookedneighbor** [comment] 2018-05-25 14:26
Can you provide the request id so we can look up the request on our end?

**Comment by crookedneighbor** [comment] 2018-05-25 14:58
I can't reproduce on my end. I get this view as I'd expect:

<img width="877" alt="screen shot 2018-05-25 at 9 56 17 am" src="https://user-images.githubusercontent.com/2916945/40551323-28c04c24-6002-11e8-8b7e-bf5bb0d70f72.png">

**Comment by jmannau** [comment] 2018-05-25 21:46
Hi,
Here is a request id where it occurred

```
{
  "data" : {
    "tokenizeCreditCard" : null
  },
  "extensions" : {
    "requestId" : "be1da38e-84c9-430b-8675-ef0f9abd6f97"
  }
}
```

**Comment by crookedneighbor** [comment] 2018-05-29 21:01
I was able to reproduce this. We'll work on getting it fixed. Thanks for the report!

**Comment by alexgenco** [comment] 2018-05-30 18:18
@jmannau We have a fix for this in the pipeline, however if you want a quick fix, I believe you can just enable cvv or avs rules in your sandbox control panel: https://articles.braintreepayments.com/guides/fraud-tools/basic/avs-cvv-rules. Let us know if that helps.

**Comment by jmannau** [comment] 2018-05-31 06:34
Thanks Team. @alexgenco you beat me to it. Thanks for the work around. Out of curiosity, once fixed, will I need to update the drop-in library or is it a server fix? 
Thanks very much for your quick response! :D

**Comment by crookedneighbor** [comment] 2018-05-31 11:52
It's a fix that will happen on the server, so no need to upgrade.

**Comment by demerino** [comment] 2018-06-19 18:10
The server side fix for this should be out. Let us know if there are any other issues.

**Closed by demerino** 2018-06-19 18:10 UTC
