### ISSUE TITLE
Test Credit Card number gets accepted in production

### ISSUE THREAD

**Issue by beworker** [braintree/braintree-web-drop-in#90] opened 2017-03-08 08:56 UTC
### General information

* SDK/Library version: dropin/1.0.0-beta.4/js/dropin.min.js
* Environment: Production
* Browser and OS Chrome 56.0.2924.87 (64-bit) on MacOS 10.12.3

### Issue description
As a user I enter test Visa credit card data (4111 1111 1111 1111) into the fields provided by drop-in UI. 

#### Observed behaviour
UI accepts given credit card and animates into the "OK check in a circle" state.

####  Expected behaviour
Drop-in UI shall show an error saying that the entered credit card is not valid when running in Production environment.

**Comment by crookedneighbor** [comment] 2017-03-09 17:03
This is expected behavior.

Drop-in's client side validation does not check whether or not the card is a real card, just whether or not it looks like a credit card number (is luhn 10 valid, matches patterns for bin ranges for the type of card).

The only way to determine if a card is a real card would be to actually transact against it.

Alternatively, for the test cards, you could provide the SDK with a list of known sandbox cards and provide logic to check whether or not you're in a non-prod environment, but that would increase the file size of the SDK for very little payoff.

Going to close this now, but if this doesn't address your concern, let me know!

**Closed by crookedneighbor** 2017-03-09 17:03 UTC
