### ISSUE TITLE
Postal code autofill incorrectly produces error on iOS Chrome

### ISSUE THREAD

**Issue by waraulin** [braintree/braintree-web-drop-in#892] opened 2023-07-06 00:19 UTC
### General information

* SDK/Library version: braintree/web/3.85.3
* Environment: Sandbox & Production
* Browser and OS Chrome 114.0.5735.124 on iOS 16.2

### Issue description

Steps to reproduce:
This is happening in both production and sandbox on my site but is also reproducible using the [Braintree drop-in demo](https://braintree.github.io/braintree-web-drop-in/). I am able to get the error to clear on the demo form by clicking around but on my drop-in instance the error won't clear (I would link my site here but I don't want to subject you to our cart abandonment email campaign). It seems to me like it is still a bug even if the error clears after clicking around. 

Steps to reproduce:
1. Navigate to https://braintree.github.io/braintree-web-drop-in/
2. Enter valid visa test card info
3. Click into the Postal Code field and select one of the autofill postal code values that the chrome/iOS keyboard suggests
4. Verify that you are shown the Postal Code error `Please fill out a postal code.` while you have a valid postal code in the input.
5. Using the following code verify that the postal code field is valid at the same time that the error is visible
  `instance.on('card:validityChange', function(event) {
                        if(event.emittedBy === 'postalCode' && event.fields.postalCode.isValid) {
                            console.log("postal code is valid");
                        } else if(event.emittedBy === 'postalCode' && !event.fields.postalCode.isValid) {
                            console.log("postal code is NOT valid");
                        }
                    });`

I was hoping to manually force the dropin to revalidate when the card:validityChange fires but haven't yet found a way to do that. If anyone has any insight as to how to do that or why my dropin form wouldn't be clearing errors after the field blurring that would be appreciated.

Thanks for the help!! Screenshots below.

![IMG_41EEBAE7D0FB-1](https://github.com/braintree/braintree-web-drop-in/assets/6526153/f0c7cfa0-6b82-418e-9404-d866fe0631e1)
![IMG_CCC93ECAB318-1](https://github.com/braintree/braintree-web-drop-in/assets/6526153/463efe3d-1020-40b5-95c8-9d2c0382271f)

**Comment by hollabaq86** [comment] 2023-07-07 19:23
👋 @waraulin are you still seeing this issue on the latest version of the Drop-In, 1.38.1? There's been a number of updates since the version you mentioned, including a few bug fixes, I just want to confirm this is still an issue on the latest version.

**Comment by waraulin** [comment] 2023-07-07 20:17
Hey @hollabaq86 thanks for the reply! I should have tried updating before even opening this ticket - sorry about that. I just updated to the latest drop-in version and can confirm that my drop-in behavior now matches that of the demo here: https://braintree.github.io/braintree-web-drop-in/

I still see the postal code error upon autofilling the postal code value but as soon as I click anywhere else on screen (as soon as the postal code field blurs) the error is cleared. I think this is still a small bug since the error message shows when a valid postal code is present, but I think the current behavior is totally acceptable for me for production. My steps to reproduce above are still valid. I'll leave this ticket open in case you think you want to address it but I am content with the current behavior in v1.38.1. Thank you!!

**Comment by jplukarski** [comment] 2023-11-28 22:37
I can reproduce the issue as described as above. Adding a card to our backlog to see if there is anything we can do to fix this issue or if it's just the way Chrome autofill works. For internal tracking -> 29300

**Comment by ibooker** [comment] 2024-01-08 23:12
@waraulin Can you confirm if this issue is still present after updating to a recent version of Chrome? We're not able to duplicate this issue with Chrome 120.

**Comment by waraulin** [comment] 2024-01-09 17:51
@ibooker - confirmed I can no longer reproduce this with my iPhone on Chrome 120. Thanks!!

**Comment by ibooker** [comment] 2024-01-09 18:26
Issue resolved in Chrome 120

**Closed** 2024-01-09 18:26 UTC
