### ISSUE TITLE
Missing translation and CSS bug

### ISSUE THREAD

**Issue by MrMooky** [braintree/braintree-web-drop-in#134] opened 2017-04-24 08:51 UTC
### General information

* SDK/Library version: 1.0.0 Beta 6
* Environment: Sandbox
* Browser and OS Chrome 57.0.2987.133 (64-bit)) on MacOS 10.12.4

### Issue description

Screenshot:

![screen shot 2017-04-24 at 10 47 10 am](https://cloud.githubusercontent.com/assets/3603346/25329449/0326ed00-28dc-11e7-9160-0f0a4f1b85ca.png)

Both issues are visible in the screenshot:

- Translation is not correct. The DropIn-UI is set to de_DE (works fine for the other parts)
- CSS is buggy. Element has a max-width of 148px, but the main container is larger by default

**Comment by crookedneighbor** [comment] 2017-04-24 13:24
Thanks for reporting.

The translation issue will be fixed in https://github.com/braintree/braintree-web-drop-in/pull/135

The max-width issue looks to me like a duplicate of https://github.com/braintree/braintree-web-drop-in/issues/86

**Closed** 2017-04-27 01:35 UTC
