### ISSUE TITLE
paymentMethodRequestable triggers when clicking on Choose another way to pay

### ISSUE THREAD

**Issue by greg-super** [braintree/braintree-web-drop-in#582] opened 2019-12-06 08:05 UTC
Hi Guys,

When using paymentMethodRequestable, it triggers when clicking on "Choose another way to pay".
Basically when I have pre-vaulted payments methods and I click on "Choose another way to pay" it shows the options Credit Card, Paypal etc, if I click on an option but decide to pay another way and click "Choose another way to pay" to get to the options, paymentMethodRequestable triggers with the previously vaulted payment method.

Technically yes there is a payment method and yes it is selected however I don't think this is the desired effect. 

I thought paymentMethodRequestable was triggered only when a payments flow is completed.

The only way I can get it to work is by using instance.clearSelectedPaymentMethod() but its not ideal

Im using both paymentMethodRequestable and paymentMethodIsSelected
* SDK/Library version: dropin 1.21.0 
* Environment: Sandbox
* Browser and OSZ: Firefox 70.0.1/Windows 10
this is my code:
 braintree.dropin.create({
		authorization: 'clientToken',
		container: '#dropin',
		paypal: {
			flow: 'vault'
		}	
    }, function (createErr, instance) {
		instance.clearSelectedPaymentMethod();		
		function sendNonceToServer() {
			instance.requestPaymentMethod(function (err, payload) {
				document.querySelector('#nonce').value = payload.nonce;
				$("#checkout").submit();				
		       });
		}
		submitButton.addEventListener('click', sendNonceToServer);
		instance.on('paymentMethodRequestable', function (event) {
		  if (event.paymentMethodIsSelected == true) {
			sendNonceToServer();
		  }
		});  
    });

**Comment by crookedneighbor** [comment] 2019-12-06 14:57
Pretty sure this is a duplicate of https://github.com/braintree/braintree-web-drop-in/issues/461

In that, the naming and purpose of these events is not always clear. 

I believe this is expected behavior for this event at this time. When "Choose another way to pay" is selected, Drop-in reports that the payment method is no longer requestable, but when it switches back to the the payment method selection view, it auto-selects a pre-added card and reports that a payment method is now requestable.

We're looking for ways to improve the events and document more clearly how they should be used, but I think that's all covered in the previous issue I posted, so I'm going to close this one.

**Closed by crookedneighbor** 2019-12-06 14:57 UTC
