### ISSUE TITLE
"Network error. Please try again." when enter invalid card

### ISSUE THREAD

**Issue by ChrisHSandN** [braintree/braintree-web-drop-in#436] opened 2018-09-27 12:02 UTC
### General information

* SDK/Library version: 3.34.0
* Environment: Production

### Issue description

Enter card number: 4111 1111 1111 1111
Enter expiry date: 01 / 2025
Submit
Shows error "Network error. Please try again." in red at the bottom

![image](https://user-images.githubusercontent.com/13466620/46144403-b8e72e80-c254-11e8-9c29-41db2a9c657d.png)

### Expected behavior

Either "Network Error" is a very user unfriendly way of saying the card number is not valid or this is causing a real error in the client/server side. Either way it seems like a bug.

**Comment by crookedneighbor** [comment] 2018-09-28 16:04
I'm not experiencing this error in my testing. 

That error should only occur when the Braintree gateway cannot be contacted for some reason. Can you inspect the error? It should include details about the original error.

**Comment by ChrisHSandN** [comment] 2018-10-01 08:13
I investigated the API calls made during the process action and I think it is this one causing the problem:

Request to https://payments.braintree-api.com/graphql
```
{
   "clientSdkMetadata":{
      "source":"client",
      "integration":"dropin2",
      "sessionId":"74a850ee-e575-40b6-8ae9-9bf1dad3eaf1"
   },
   "query":"mutation TokenizeCreditCard($input: TokenizeCreditCardInput!) {   tokenizeCreditCard(input: $input) {     token     creditCard {       brandCode       last4       binData {         prepaid         healthcare         debit         durbinRegulated         commercial         payroll         issuingBank         countryOfIssuance         productId       }     }   } }",
   "variables":{
      "input":{
         "creditCard":{
            "number":"4111111111111111",
            "expirationMonth":"01",
            "expirationYear":"2025"
         },
         "options":{
            "validate":true
         }
      }
   },
   "operationName":"TokenizeCreditCard"
}
```

Response
```
{  
   "data":{  
      "tokenizeCreditCard":null
   },
   "errors":[  
      {  
         "message":"An unknown error occurred.",
         "locations":[  
            {  
               "line":1,
               "column":67
            }
         ],
         "path":[  
            "tokenizeCreditCard"
         ],
         "extensions":{  
            "errorType":"unknown_error",
            "errorClass":"VALIDATION"
         }
      }
   ],
   "extensions":{  
      "requestId":"7d6e6a6b-a056-4013-a31d-5d0db2668ffd"
   }
}
```

**Comment by jackellenberger** [comment] 2018-10-01 18:20
Thanks for that info, @ChrisHSandN! We've found the issue on the backend and will update you when the fix is released. The problem isn't that you're getting an error, you should be - you can't tokenize a test credit card number like 4111111111111111 in production - We're just not surfacing that correctly. 

Let us know if you're seeing issues with other numbers as well! There might be something additional afoot.

**Comment by crookedneighbor** [comment] 2018-10-08 22:18
We're doing some more refining on the error handling. Will report back here when it is released.

**Comment by crookedneighbor** [comment] 2018-10-30 19:50
This should be fixed now. Thanks for the report!

**Closed by crookedneighbor** 2018-10-30 19:50 UTC
