### ISSUE TITLE
Custom Fonts on Hosted Fields

### ISSUE THREAD

**Issue by ryanjwilke** [braintree/braintree-web-drop-in#303] opened 2017-10-25 13:09 UTC
I'm trying to figure out how I could use a custom font inside of the "hosted fields" on the Drop-in UI, but I'm coming up short. Any chance there's a way to inject the Typekit `script` or `@import` URLs to load the custom font?

### Example Style Overrides
```js
dropin.create({
  authorization: '...',
  container: '...',
  card: {
    overrides: {
      styles: {
        input: {
          'color': '#313a44',
          'font-weight': '500',
          'font-family': '"museo-sans-rounded", "Museo Sans Rounded", Arial, sans-serif'
        },
      },
    },
  },
})
```

**Comment by crookedneighbor** [comment] 2017-10-25 13:25
This is a duplicate of https://github.com/braintree/braintree-web/issues/75

The highlights are:

> For PCI and security reasons, we can't simply include third-party code into Hosted Fields, regardless of the party.

> to qualify for SAQ A compliance the iframes and pages served by your PCI DSS compliant payment provider must have all elements served originate only and directly from the payment provider.
> In the case of Google Fonts, the fonts would originate from Google and would force SAQ A-EP compliance.

> The interpretation of PCI DSS v3 held by Braintree and the external PCI quality assessors that verify our compliance forbid elements originating from any third party within our Hosted Fields solution.
> Barring a more lenient revision to PCI DSS we cannot allow usage of services such as Google Fonts within Hosted Fields and continue to claim SAQ A.
> Other payment providers may offer more lenient solutions while claiming SAQ A compliance, but Braintree has historically erred on the side of safety when abiding by PCI regulations.

The examples from the issue I posted are talking about Google fonts, but the same applies for Typekit.

**Closed by crookedneighbor** 2017-10-25 13:25 UTC
