### ISSUE TITLE
Strange dependency on the package "8"

### ISSUE THREAD

**Issue by raRaRa** [braintree/braintree-web-drop-in#490] opened 2019-04-03 10:21 UTC
I upgraded `braintree-web-drop-in` today and noticed a new dependency on a package called '8'.

Ref: https://github.com/braintree/braintree-web/issues/422
8: https://www.npmjs.com/package/8

**Comment by crookedneighbor** [comment] 2019-04-03 12:34
Closing this as a duplicate of the issue you posted on the braintree-web repo: https://github.com/braintree/braintree-web/issues/422

**Closed by crookedneighbor** 2019-04-03 12:34 UTC
