### ISSUE TITLE
Full CSP support

### ISSUE THREAD

**Issue by rublon-mra** [braintree/braintree-web-drop-in#904] opened 2023-09-25 13:22 UTC
### General information

* SDK/Library version: 1.40.2 (latest)
* Environment: Sandbox
* Browser and OS Chrome 117.0.5938.92 (64-bit) on Windows 10

### Issue description

Hello, I'm trying to implement a Content-Security-Policy header in my application with Angular 16.
My CSP: 
`frame-ancestors 'none';base-uri 'self';connect-src 'self' my-api-domain.com api.sandbox.braintreegateway.com client-analytics.sandbox.braintreegateway.com *.braintree-api.com *.cardinalcommerce.com;media-src 'self';object-src 'none';script-src 'self' 'nonce-random_nonce_value' js.braintreegateway.com assets.braintreegateway.com songbirdstag.cardinalcommerce.com;style-src 'self' 'nonce-random_nonce_value' assets.braintreegateway.com`

When the list of vaulted payment methods loads then in the browser console I see information about blocking inline style:

> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-random_nonce_value' assets.braintreegateway.com". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution.
> 
> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-random_nonce_value' assets.braintreegateway.com". Either the 'unsafe-inline' keyword, a hash ('sha256-BG95MWPP0U+f27TYIqtFSm4Gz7c65uJZGaT78W6hd98='), or a nonce ('nonce-...') is required to enable inline execution.
> 
> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-random_nonce_value' assets.braintreegateway.com". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution.
> 
> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-random_nonce_value' assets.braintreegateway.com". Either the 'unsafe-inline' keyword, a hash ('sha256-Y4bPrOO9IjhWPHXYbbWr91LU9SrikejNy+B8pYASCLM='), or a nonce ('nonce-...') is required to enable inline execution.

Do I really need to add 'unsafe-inline' for the style-src directive?
Without applying this change, the "Purchase Authentication" (3D Secure) window appears under the DropIn UI and there is no way to pay.
I will be grateful for any help.

**Comment by rublon-mra** [comment] 2023-09-26 06:56
Hi, I verified this even before I added this issue. I set all these directives for Content Security Policy (from "Basic Directives" and "3D Secure Specific Directives" sections).
My problems come from style-loader/addStyles.js.

My CSP:
`frame-ancestors 'none';base-uri 'self';connect-src 'self' my-api-domain.com api.sandbox.braintreegateway.com client-analytics.sandbox.braintreegateway.com *.braintree-api.com *.cardinalcommerce.com;media-src 'self';object-src 'none';script-src 'self' 'nonce-random_nonce_value' js.braintreegateway.com assets.braintreegateway.com songbirdstag.cardinalcommerce.com;style-src 'self' 'nonce-random_nonce_value' assets.braintreegateway.com`

**Comment by jplukarski** [comment] 2023-11-28 22:01
Hey @rublon-mra , thanks for your patience as we had to shift our prioritize for the Black Friday/Cyber Monday season. We are going to pick up investigations into this issue.

To clarify, are you still seeing these errors when not setting `unsafe-inline` in your `style-source` directives?

> Angular works in such a way that it adds nonces only for styles and scripts, which are created right away when the index.html is generated, and here these styles are added after the DropinUI is displayed.

We are going to investigate, though it might be that this is a limitation with Angular and the Drop-In. For internal reference of this issue -> 29294

**Comment by rublon-mra** [comment] 2023-11-29 08:03
Hi @jplukarski , yes. I still have a problem with this.
I would be grateful for your help.

**Comment by jplukarski** [comment] 2023-11-29 21:59
Hey @rublon-mra ,

After some further investigation, it looks like this is a limitation in Angular 16 with CSP and dynamically added styles. [This article](https://www.innoq.com/en/blog/2023/06/style-nonces-for-csp-in-angular-16/) explains it very well:
> There are some things to keep in mind, though: This setup covers the core Angular functionality. If you use additional frameworks that also add <style> tags dynamically, you might need additional configuration of even scripting to ensure that their styles still work. So while adding nonces for styles is not a silver bullet, I think it is a relatively easy way to improve on your existing CSP and secure your application a bit better.

We are going to close this issue since it is not a bug we can fix within our SDK. Let us know if there is anything else we can help you out with.

**Closed by jplukarski** 2023-11-29 21:59 UTC

**Comment by jordan-bite** [comment] 2024-07-11 18:40
I feel this is something that can be fixed by accepting a `nonce` argument which would be added to all the `script` and `style` tags added by the sdk. Can someone explain why I'm wrong?
