### ISSUE TITLE
DropIn Autofill issues

### ISSUE THREAD

**Issue by alexbohariuc** [braintree/braintree-web-drop-in#693] opened 2021-02-04 08:55 UTC
### General information

* SDK/Library version: 1.25.0
* Environment: Sandbox and production
* Browser and OS Chrome 88.0.4324.96 / OSX 11.1 

### Issue description

I'm using the Dropin-UI on a donation form, with PHP on the server side.
Everything seems to work smoothly, except for the card details autofill in Chrome.

When the user chooses to autofill the card details I get the following error:
DropinError: No Payment Method is Available

And the Dropin looks like this:

![Screenshot 2021-02-04 at 10 37 47](https://user-images.githubusercontent.com/2670791/106868199-2a620200-66d7-11eb-8c1c-40cb16d4f391.png)

This is how I'm configuring the Drop-in UI:
```

						braintree.dropin.create(
							{
								authorization: response.token,
								selector: "#bt-dropin-recurr",
								card: {
									cardholderName: {
										required: true
									}
								},
								paypal: {
									flow: "vault"
								},
							},
```

Any ideas what I'm doing wrong?
If the card details are filled in manually everything works OK. 

Thanks!

**Comment by crookedneighbor** [comment] 2021-02-04 13:19
This is a duplicate of https://github.com/braintree/braintree-web-drop-in/issues/676

Update to v1.26.0 for the fix.

**Closed by crookedneighbor** 2021-02-04 13:19 UTC
